#!/bin/bash

#performs tests if there are changes in the backend branch
if [[ $(git diff --name-only HEAD) =~ (^|\ )backend/.* ]]; then
  echo "There are changes! Running tests!"

  cd ./backend || exit
  mvn test
  cd ..

  if [ $? -ne 0 ]
  then
      echo "Tests failed. Aborting push."
      exit 1
  fi
fi
